/** Companion-authored content, reused from our listening trainer; no LCWO corpus. */
export const COPY_CONTENT_VERSION = 'companion-copy-2026-09-29';

export const COPY_MORSE: Record<string, string> = {
  A: '.-',
  B: '-...',
  C: '-.-.',
  D: '-..',
  E: '.',
  F: '..-.',
  G: '--.',
  H: '....',
  I: '..',
  J: '.---',
  K: '-.-',
  L: '.-..',
  M: '--',
  N: '-.',
  O: '---',
  P: '.--.',
  Q: '--.-',
  R: '.-.',
  S: '...',
  T: '-',
  U: '..-',
  V: '...-',
  W: '.--',
  X: '-..-',
  Y: '-.--',
  Z: '--..',
  '0': '-----',
  '1': '.----',
  '2': '..---',
  '3': '...--',
  '4': '....-',
  '5': '.....',
  '6': '-....',
  '7': '--...',
  '8': '---..',
  '9': '----.',
  '.': '.-.-.-',
  ',': '--..--',
  '?': '..--..',
  '/': '-..-.',
  '=': '-...-',
  '+': '.-.-.',
  '-': '-....-',
  '@': '.--.-.',
  ':': '---...',
  "'": '.----.',
  '(': '-.--.',
  ')': '-.--.-',
  '"': '.-..-.',
  '!': '-.-.--',
  '&': '.-...',
  ';': '-.-.-.',
  _: '..--.-',
  $: '...-..-',
};

export const COPY_ENGLISH_WORDS_BY_LENGTH: Readonly<Record<number, readonly string[]>> = {
  2: 'AM AN AS AT BE BY DO GO HE IF IN IS IT ME MY NO OF ON OR SO TO UP US WE'.split(' '),
  3: 'AIR AND ANT ARE ART ASK BAG BAT BED BIG BOX BUS BUT BUY CAN CAR CAT CUP CUT DAY DID DOG DRY EAR EAT END FAR FEW FIT FIX FLY FOR FUN GET GOT HAD HAM HAS HAT HER HIM HIS HOT HOW ICE JAM JOB JOY KEY LEG LET LOG LOT LOW MAN MAP MAY MET MIX NET NEW NOT NOW OFF OLD ONE OUR OUT OWN PAY PEN PET PUT RAN RED ROW RUN SAD SAT SAW SAY SEA SEE SET SHE SIT SIX SKY SON SUN TEA TEN THE TIE TIN TIP TOO TOP TRY TWO USE VAN WAS WAY WEB WET WHO WHY WIN YES YET YOU ZOO'.split(
    ' ',
  ),
  4: 'ABLE ALSO AWAY BACK BALL BAND BANK BARN BASE BATH BEAR BELL BIRD BLUE BOAT BOOK BOTH CALL CALM CAMP CARD CARE CASE CITY CODE COLD COME COOK COOL COPY DARK DATA DAWN DEAR DEEP DESK DOOR DOWN DRAW DROP EACH EAST EASY EDGE EVEN EVER FACE FACT FAIR FALL FAST FEEL FIND FINE FIRE FISH FIVE FLAG FOOD FOOT FOUR FREE FROM FULL GAME GATE GIFT GIVE GLAD GOAL GOLD GOOD GROW HAND HARD HAVE HEAR HELP HERE HIGH HILL HOLD HOME HOPE HOUR IDEA INTO IRON JOIN JUMP JUST KEEP KIND KITE KNOW LAKE LAND LAST LATE LEAF LEFT LIFE LIKE LINE LINK LIST LIVE LONG LOOK LOVE LUCK MADE MAIL MAIN MAKE MANY MARK MEAL MEAN MEET MIND MISS MODE MOON MORE MOST MOVE MUCH NAME NEAR NEED NEXT NICE NINE NOTE OPEN OVER PAGE PAIR PARK PART PASS PAST PATH PINE PLAN PLAY PLUS POOL POST PULL PURE PUSH RACE RAIN READ REAL REST RICE RIDE RING RISE ROAD ROCK ROOM ROSE RULE SAFE SAID SAIL SAME SAND SAVE SEAT SEED SEEK SEEM SEEN SELF SEND SHIP SHOP SHOW SIDE SIGN SING SITE SIZE SLOW SNOW SOFT SOME SONG SOON STAR STAY STEP STOP SUCH SURE TAKE TALK TALL TEAM TELL TENT TEST TEXT THAN THAT THEM THEN THEY THIN THIS TIME TINY TOLD TONE TOOL TOWN TREE TRIP TRUE TUNE TURN TYPE UNIT UPON VERY VIEW WAIT WALK WALL WARM WAVE WEEK WELL WENT WERE WEST WHAT WHEN WIDE WILD WILL WIND WING WIRE WISE WISH WITH WOOD WORD WORK YARD YEAR YOUR ZERO ZONE'.split(
    ' ',
  ),
  5: 'ABOUT ABOVE ADULT AFTER AGAIN AGENT AGREE AHEAD ALONE ALONG AMONG ANGEL APPLE APPLY APRIL AUDIO AVOID BEACH BEGIN BELOW BIRTH BLACK BLANK BLEND BLOCK BLOOM BOARD BRAIN BRAVE BREAD BREAK BRICK BRING BROAD BROWN BUILD CABIN CABLE CARRY CATCH CAUSE CHAIR CHART CHECK CHILD CHOSE CLEAN CLEAR CLIMB CLOCK CLOSE CLOUD COAST COLOR COULD COUNT COURT COVER CRAFT CREAM CROSS CROWD DAILY DANCE DEPTH DOUBT DREAM DRINK DRIVE EARLY EARTH EIGHT ENJOY ENTER EQUAL EVENT EVERY EXACT EXTRA FAITH FIELD FIFTY FINAL FIRST FLAME FLOAT FLOOR FOCUS FORCE FORTY FOUND FRESH FRONT FRUIT FULLY FUNNY GIANT GIVEN GLASS GLOBE GRACE GRAND GRANT GRASS GREAT GREEN GROUP GUESS GUIDE HAPPY HEART HEAVY HELLO HORSE HOTEL HOUSE HUMAN IMAGE INNER INPUT ISSUE KNOWN LARGE LATER LAUGH LAYER LEARN LEAST LEAVE LEVEL LIGHT LIMIT LIVED LOCAL LOOSE LOVED LOWER LUCKY LUNCH MAGIC MAJOR MARCH MATCH MAYBE METAL MIGHT MINOR MODEL MONEY MONTH MOTOR MOUNT MOUSE MOUTH MUSIC NEVER NIGHT NOISE NORTH NOTES NOVEL NURSE OCEAN OFFER OFTEN ORDER OTHER OWNER PAPER PARTY PAUSE PEACE PHONE PHOTO PIANO PIECE PILOT PLACE PLAIN PLANE PLANT PLATE POINT POWER PRESS PRICE PRIDE PRIME PRINT PRIOR PROOF PROUD QUEEN QUICK QUIET QUITE RADIO RAISE RANGE REACH READY RIGHT RIVER ROUND ROUTE ROYAL RURAL SCALE SCENE SCORE SENSE SERVE SEVEN SHADE SHAKE SHALL SHAPE SHARE SHARP SHEET SHELF SHELL SHIFT SHINE SHIRT SHORT SHOWN SIGHT SINCE SKILL SLEEP SLOPE SMALL SMART SMILE SMOKE SOLID SOLVE SOUND SOUTH SPACE SPARE SPEAK SPEED SPEND SPOKE SPORT STAFF STAGE STAND START STATE STEEL STILL STOCK STONE STOOD STORE STORM STORY STUDY STYLE SUGAR SWEET TABLE TAKEN TEACH THANK THEIR THERE THESE THICK THING THINK THIRD THOSE THREE THROW TIGER TITLE TODAY TOPIC TOTAL TOUCH TOUGH TOWER TRACK TRADE TRAIL TRAIN TREAT TREND TRIAL TRIED TRULY TRUST TRUTH TWICE UNDER UNION UNITY UNTIL UPPER URBAN USUAL VALUE VIDEO VISIT VOICE WATER WEIGH WHEEL WHERE WHICH WHILE WHITE WHOLE WHOSE WOMAN WOMEN WORLD WORRY WORTH WOULD WRITE WRONG YOUNG YOUTH'.split(
    ' ',
  ),
  6: 'ACROSS ACTION ACTIVE ACTUAL ADVICE ALMOST ALWAYS AMOUNT ANIMAL ANSWER ANYONE AROUND ARRIVE ARTIST AUTUMN BASKET BEAUTY BEFORE BEHIND BELONG BETTER BEYOND BOTTLE BOTTOM BRANCH BRIDGE BRIGHT BROKEN BUDGET BUTTON CAMERA CANDLE CARPET CENTER CHANCE CHANGE CHARGE CHOICE CHOOSE CHORUS CIRCLE CLIENT CLOSED COFFEE COMMON CORNER COUNTY COURSE CREATE CUSTOM DANGER DEBATE DECADE DECIDE DEGREE DESIGN DETAIL DEVICE DIRECT DOUBLE DRAWER DRIVEN DURING EASILY EFFECT EFFORT EIGHTY ELEVEN ENABLE ENERGY ENGINE ENOUGH ENTIRE ESCAPE ESTATE EXCEPT EXPAND EXPECT EXPERT FAMILY FAMOUS FATHER FELLOW FINGER FINISH FLIGHT FLOWER FOLLOW FOREST FORGET FORMED FRIEND FUTURE GARDEN GENTLE GLOBAL GOLDEN GROUND GROWTH HANDLE HAPPEN HEALTH HEIGHT HIDDEN HONEST IMPACT IMPORT INCOME INDEED INSIDE INTEND ISLAND ITSELF JACKET JOINED JUNIOR KITTEN LADDER LAPTOP LATEST LAUNCH LEADER LEAGUE LENGTH LESSON LETTER LIKELY LISTEN LITTLE LIVING LOCATE LONELY LOVELY MANAGE MANNER MARKET MASTER MATTER MEDIUM MEMORY METHOD MIDDLE MINUTE MODERN MOMENT MOSTLY MOTHER MOTION MOVING MUSEUM NARROW NATION NATURE NEARBY NEARLY NEEDED NEPHEW NORMAL NOTICE NUMBER OBJECT OFFICE ONLINE OPTION ORANGE ORIGIN OUTPUT PARENT PARTLY PEOPLE PERIOD PERSON PHRASE PICKED PICNIC PLANET PLAYER PLEASE POCKET POETRY POLICY PRETTY PRINCE PUBLIC PURPLE PURSUE RABBIT RATHER REALLY REASON RECORD REDUCE REFUSE REGION RELATE REMAIN REMOTE REMOVE REPEAT REPORT RESCUE RESULT RETAIN RETURN REVIEW RHYTHM RISING ROCKET SAFELY SAMPLE SCHOOL SCREEN SEARCH SEASON SECOND SECRET SELECT SENIOR SERIES SETTLE SEVERE SHADOW SHOULD SIGNAL SILENT SILVER SIMPLE SINGLE SISTER SMOOTH SOFTLY SOURCE SPEECH SPIRIT SPRING SQUARE STABLE STAYED STEADY STREAM STREET STRIKE STRONG STUDIO SUBMIT SUDDEN SUMMER SUPPLY SWITCH SYSTEM TAKING TALENT TARGET TAUGHT TENNIS THANKS THEORY THIRTY THOUGH THREAT THROWN TIMBER TOWARD TRAVEL TRYING TWELVE TWENTY UNLESS UPDATE USEFUL VALLEY VISION VISUAL VOYAGE WALKED WEALTH WEEKLY WEIGHT WINDOW WINTER WISDOM WITHIN WONDER WOODEN WORKED WRITER YELLOW'.split(
    ' ',
  ),
  7: 'ABILITY ACCOUNT ACHIEVE ADDRESS AGAINST AIRPORT ALREADY ANOTHER ANTENNA ANYBODY APPLIED ARRIVAL ARTICLE ATTEMPT AVERAGE BALANCE BATTERY BECAUSE BEDROOM BELIEVE BENEATH BENEFIT BICYCLE BROTHER CABINET CAPITAL CAPTAIN CAREFUL CENTRAL CERTAIN CHAPTER CHARITY CHICKEN CIRCUIT CLASSIC CLOTHES COLLECT COLLEGE COMBINE COMFORT COMMAND COMPANY COMPARE COMPASS COMPILE CONCEPT CONCERN CONNECT CONTACT CONTENT CONTROL CORRECT COUNCIL COUNTER COUNTRY CRICKET CURRENT DECLARE DEFAULT DELIGHT DENSITY DESERVE DEVELOP DIGITAL DISCUSS DISPLAY DISTANT DRAWING DRIVING DYNAMIC EARLIER EASTERN ECONOMY EDITION ELDERLY ELEGANT ELEMENT EMOTION EVENING EXAMPLE EXCITED EXPLAIN EXPLORE EXPRESS EXTREME FACTORY FAILURE FEATURE FEELING FICTION FIFTEEN FINALLY FLOWERS FOLLOWS FOREVER FORGIVE FORWARD FREEDOM FURTHER GENERAL GETTING GLASSES GREATER GROCERY GROWING GROWTHS HAPPILY HEADING HEALTHY HEARING HELPFUL HERSELF HISTORY HOLIDAY HOWEVER HUNDRED HUSBAND IMAGINE IMPROVE INCLUDE INITIAL INSIGHT INSTANT INSTEAD INVOLVE JOURNEY JUSTICE KITCHEN LANDING LANTERN LARGELY LASTING LEADING LEARNED LEATHER LEAVING LIBRARY LIMITED MACHINE MANAGER MARRIED MEANING MEASURE MEDICAL MEETING MESSAGE MILLION MINERAL MINUTES MISSING MISSION MORNING MUSICAL NATURAL NEITHER NETWORK NOTHING NUMBERS OBVIOUS OFFICER OPINION OUTDOOR OUTLINE OUTSIDE OVERALL PACKAGE PAINTED PARTNER PASSAGE PATIENT PATTERN PERFECT PERHAPS PICTURE PLANNED PLASTIC PLEASED POPULAR PRESENT PREVENT PRIMARY PRIVATE PROBLEM PROCESS PRODUCE PROGRAM PROJECT PROMISE PROTECT PROVIDE PURPOSE QUALITY QUICKLY QUIETLY RAILWAY READING RECEIVE REFLECT REGULAR RELATED RELEASE REMAINS REMINDS REPLACE REQUEST RESPECT RESPOND RESTORE RETREAT ROUTINE RUNNING SCIENCE SECTION SERIOUS SERVICE SESSION SEVERAL SHARING SHELTER SHOWING SILENCE SIMILAR SINGING SITTING SOCIETY SOMEONE SPECIAL STATION STORAGE STRANGE STRETCH STUDENT SUBJECT SUCCEED SUCCESS SUGGEST SUPPORT SUPPOSE TEACHER THOUGHT THROUGH TONIGHT TOTALLY TOURIST TOWARDS TRAFFIC TROUBLE TRUSTED TUESDAY TURNING TYPICAL UNIFORM UNKNOWN USUALLY VARIETY VARIOUS VILLAGE WAITING WALKING WEATHER WEBSITE WEEKEND WELCOME WESTERN WHETHER WILLING WITHOUT WORKING WRITING'.split(
    ' ',
  ),
  8: 'ABSOLUTE ACADEMIC ACCURACY ACTUALLY ADJUSTED ADVANCED ADVISORS AIRCRAFT ALTHOUGH ANALYSIS ANYTHING APPEARED APPROACH APPROVAL ARGUMENT ARRANGED ASSEMBLY ATTACHED ATTEMPTS ATTITUDE AUDIENCE BALANCED BASEBALL BATHROOM BIRTHDAY BOUNDARY BREAKING BREATHED BRIGHTER BUILDING BUSINESS CALENDAR CAMPAIGN CAPACITY CAPTURED CARRIAGE CATEGORY CAUTIOUS CEREMONY CHILDREN CLEANING CLEARING CLIMBING CLOTHING COACHING COMPLETE COMPUTER CONSIDER CONSTANT CONTINUE CONTRAST COPYBOOK CORRECTS COUNTING COVERAGE CREATIVE CRITICAL CURRENCY CUSTOMER DAUGHTER DAYLIGHT DECEMBER DECISION DECLARED DECREASE DELIVERY DEMANDED DESCRIBE DESIGNED DETAILED DIFFERED DIRECTLY DISTANCE DISTRICT DIVISION DOCUMENT DRAWINGS DROPPING DURATION EDUCATED ELECTION ELECTRIC ELEPHANT ENERGIES ENJOYING ENROLLED ENTIRELY ENTRANCE ENVELOPE ESTIMATE EVALUATE EVERYDAY EVERYONE EVIDENCE EXCHANGE EXERCISE EXPECTED EXPLORED EXTENDED EXTERNAL FAMILIAR FAVORITE FEEDBACK FEELINGS FESTIVAL FINISHED FLEXIBLE FLOATING FOLLOWED FOOTBALL FORECAST FOURTEEN FRACTION FREQUENT FRIENDLY FRONTIER GENEROUS GOVERNOR GRADUATE GRATEFUL GREETING HANDLING HAPPENED HOSPITAL HUNDREDS IDENTITY IMPROVED INCLUDED INCREASE INDUSTRY INFORMAL INSPIRED INSTANCE INSTRUCT INTEREST INVOLVED ISOLATED KEYBOARD LANGUAGE LEARNING LIFETIME LISTENER LOCATION MAGAZINE MAINTAIN MAJORITY MATERIAL MEASURED MEETINGS MEMORIES MERCHANT MIDNIGHT MINORITY MODERATE MOUNTAIN MOVEMENT MULTIPLE NATIONAL NEIGHBOR NOTEBOOK NOVEMBER OBSERVED OCCASION OFFICIAL OPENINGS OPERATOR ORDINARY ORIGINAL OUTDOORS OVERCOME PAINTING PERSONAL PICTURES PLANNING PLEASANT POSITION POSSIBLE POTATOES PRACTICE PREPARED PRESERVE PRESSURE PREVIOUS PRINCESS PROBABLY PROGRESS PROJECTS PROMISED PROPERLY PROPOSAL PROVIDER QUESTION RAINFALL REACTION RECEIVED RECORDED RECOVERY REFERRED REGISTER RELATION RELAXING RELEASED RELIABLE REMEMBER REPEATED REPLACED REQUIRED RESEARCH RESPONSE RETAINED RETURNED REVIEWED REVISION ROADWAYS SANDWICH SCHEDULE SECONDLY SELECTED SEMESTER SENTENCE SEPARATE SHOULDER SINGULAR SLIGHTLY SMOOTHER SOFTWARE SOLUTION SOMEBODY SOMEWHAT SPEAKING SPECIFIC STANDARD STANDING STARTING STATIONS STEADILY STOPPING STRAIGHT STRATEGY STRENGTH STUDENTS SUITABLE SUNLIGHT SUNSHINE SUPPLIED SURPRISE SWIMMING TEACHING TERMINAL THANKFUL THINKING THIRTEEN THOUGHTS TOGETHER TOMORROW TRACKING TRAINING TRANSFER TREASURE TROPICAL ULTIMATE UMBRELLA UNCOMMON UNDERWAY UNIVERSE UNLIKELY UPDATING UPLOADED VACATION VALUABLE VERTICAL VICTORIA VISITORS WATCHING WHATEVER WHENEVER WHEREVER WILDLIFE WORKSHOP YOURSELF'.split(
    ' ',
  ),
};

export const COPY_WORD_COLLECTIONS = {
  english: ['A', 'I', ...Object.values(COPY_ENGLISH_WORDS_BY_LENGTH).flat()],
  short: ['A', 'I', ...COPY_ENGLISH_WORDS_BY_LENGTH[2], ...COPY_ENGLISH_WORDS_BY_LENGTH[3]],
  abbreviations:
    'AGN ANT BK CQ CW DE DX ES FB GA GE GM GN HI HR HW K KN NR OM OP PSE R RIG RPT RST RX SK SRI TNX TU TX UR VY WX XYL YL 73 88'.split(
      ' ',
    ),
  qcodes:
    'QRA QRB QRG QRH QRI QRK QRL QRM QRN QRO QRP QRQ QRS QRT QRU QRV QRW QRX QRZ QSA QSB QSL QSO QSP QSY QTH QTR'.split(
      ' ',
    ),
} as const;

/** Original practice sentences, not copied curriculum, quotations, or proverbs. */
export const COPY_SENTENCES = [
  'THE SMALL RADIO SITS BESIDE THE WINDOW.',
  'WE HEARD A CLEAR SIGNAL FROM THE HILL.',
  'PLEASE SEND YOUR NAME AGAIN.',
  'A QUIET MORNING IS A GOOD TIME TO PRACTICE.',
  'THE ANTENNA IS ABOVE THE GARDEN.',
  'I WILL LISTEN FOR YOU AFTER LUNCH.',
  'YOUR LAST WORD WAS LOST IN THE NOISE.',
  'WE MOVED THE DESK CLOSER TO THE DOOR.',
  'THE BATTERY LASTED ALL AFTERNOON.',
  'THREE FRIENDS WALKED TO THE LAKE.',
  'PLEASE WAIT WHILE I FIND MY LOG.',
  'THE RAIN STOPPED BEFORE OUR WALK.',
  'MY FIRST CONTACT TODAY WAS VERY CLEAR.',
  'A RED BIRD LANDED ON THE FENCE.',
  'WE WILL TRY A LOWER POWER LEVEL.',
  'THE NEXT TRAIN ARRIVES AT NOON.',
  'PLEASE LEAVE A LITTLE SPACE BETWEEN WORDS.',
  'THE NIGHT SKY WAS FULL OF STARS.',
  'I WROTE YOUR CALL IN MY NOTEBOOK.',
  'THE NEW CABLE REACHES THE SHED.',
  'OUR GROUP MEETS ON MONDAY EVENING.',
  'THE WIND WAS STRONG NEAR THE COAST.',
  'THANK YOU FOR AN ENJOYABLE CONTACT.',
  'I CAN HEAR YOU BETTER NOW.',
];
